enum {
	TEX_bottom_stage_point_panel_alpha,
	TEX_bottom_virus_flash_panel_alpha,
	TEX_top_gamelv_contents_alpha,
	TEX_top_score_panel_1p_alpha,
	TEX_top_score_panel_2p_alpha,
	TEX_top_speed_contents_alpha,
	TEX_top_speed_panel_alpha,

	TEX_bottom_flash_panel,
	TEX_bottom_stage_panel,
	TEX_top_gamelv_contents,
	TEX_top_score_panel_1p,
	TEX_top_score_panel_2p,
	TEX_top_speed_contents,
	TEX_top_speed_panel,

	TEX_bottom_point_panel,
	TEX_bottom_virus_panel,
	TEX_top_gamelv_panel,
	TEX_top_gamelv_panel_alpha,
	TEX_top_ohanasi_panel,
	TEX_top_ohanasi_panel_alpha,
	TEX_top_viruslv_panel,
	TEX_top_viruslv_panel_alpha,
};
